// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtocolId.proto

#include "ProtocolId.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
}  // namespace Protocol
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_ProtocolId_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ProtocolId_2eproto = nullptr;
const uint32_t TableStruct_ProtocolId_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_ProtocolId_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020ProtocolId.proto\022\010Protocol*\202\002\n\013EProtoc"
  "olId\022\r\n\tEnterGame\020\000\022\r\n\tLeaveGame\020\001\022\024\n\020Cr"
  "eateMainPlayer\020\002\022\020\n\014SyncEntities\020\003\022\016\n\nMo"
  "veEntity\020\004\022\033\n\027ModifyPlayerInformation\020\005\022"
  "\031\n\025ModifyEntityLookAtDir\020\006\022\025\n\021ModifyEnti"
  "tyState\020\007\022\022\n\016AttackToEntity\020\010\022\025\n\021HitDama"
  "geToEntity\020\t\022\r\n\tDieEntity\020\n\022\024\n\020CreatePro"
  "jectile\020\013b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_ProtocolId_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ProtocolId_2eproto = {
    false, false, 297, descriptor_table_protodef_ProtocolId_2eproto,
    "ProtocolId.proto",
    &descriptor_table_ProtocolId_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_ProtocolId_2eproto::offsets,
    nullptr, file_level_enum_descriptors_ProtocolId_2eproto,
    file_level_service_descriptors_ProtocolId_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ProtocolId_2eproto_getter() {
  return &descriptor_table_ProtocolId_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ProtocolId_2eproto(&descriptor_table_ProtocolId_2eproto);
namespace Protocol {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EProtocolId_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ProtocolId_2eproto);
  return file_level_enum_descriptors_ProtocolId_2eproto[0];
}
bool EProtocolId_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
