// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Struct.proto

#include "Struct.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR GameEntityInfo::GameEntityInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.entity_id_)*/uint64_t{0u}
  , /*decltype(_impl_.cell_pos_x_)*/0u
  , /*decltype(_impl_.cell_pos_y_)*/0u
  , /*decltype(_impl_.max_hp_)*/0u
  , /*decltype(_impl_.hp_)*/0u
  , /*decltype(_impl_.attack_)*/0u
  , /*decltype(_impl_.entity_type_)*/0
  , /*decltype(_impl_.entitye_look_at_dir_)*/0
  , /*decltype(_impl_.entity_state_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GameEntityInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GameEntityInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GameEntityInfoDefaultTypeInternal() {}
  union {
    GameEntityInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GameEntityInfoDefaultTypeInternal _GameEntityInfo_default_instance_;
PROTOBUF_CONSTEXPR GameMonsterInfo::GameMonsterInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.entity_info_)*/nullptr
  , /*decltype(_impl_.monster_id_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GameMonsterInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GameMonsterInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GameMonsterInfoDefaultTypeInternal() {}
  union {
    GameMonsterInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GameMonsterInfoDefaultTypeInternal _GameMonsterInfo_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_Struct_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Struct_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Struct_2eproto = nullptr;

const uint32_t TableStruct_Struct_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::GameEntityInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::GameEntityInfo, _impl_.entity_id_),
  PROTOBUF_FIELD_OFFSET(::Protocol::GameEntityInfo, _impl_.cell_pos_x_),
  PROTOBUF_FIELD_OFFSET(::Protocol::GameEntityInfo, _impl_.cell_pos_y_),
  PROTOBUF_FIELD_OFFSET(::Protocol::GameEntityInfo, _impl_.max_hp_),
  PROTOBUF_FIELD_OFFSET(::Protocol::GameEntityInfo, _impl_.hp_),
  PROTOBUF_FIELD_OFFSET(::Protocol::GameEntityInfo, _impl_.attack_),
  PROTOBUF_FIELD_OFFSET(::Protocol::GameEntityInfo, _impl_.entity_type_),
  PROTOBUF_FIELD_OFFSET(::Protocol::GameEntityInfo, _impl_.entitye_look_at_dir_),
  PROTOBUF_FIELD_OFFSET(::Protocol::GameEntityInfo, _impl_.entity_state_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::GameMonsterInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::GameMonsterInfo, _impl_.monster_id_),
  PROTOBUF_FIELD_OFFSET(::Protocol::GameMonsterInfo, _impl_.entity_info_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::GameEntityInfo)},
  { 15, -1, -1, sizeof(::Protocol::GameMonsterInfo)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_GameEntityInfo_default_instance_._instance,
  &::Protocol::_GameMonsterInfo_default_instance_._instance,
};

const char descriptor_table_protodef_Struct_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014Struct.proto\022\010Protocol\032\nEnum.proto\"\226\002\n"
  "\016GameEntityInfo\022\021\n\tentity_id\030\001 \001(\004\022\022\n\nce"
  "ll_pos_x\030\002 \001(\r\022\022\n\ncell_pos_y\030\003 \001(\r\022\016\n\006ma"
  "x_hp\030\004 \001(\r\022\n\n\002hp\030\005 \001(\r\022\016\n\006attack\030\006 \001(\r\022."
  "\n\013entity_type\030\007 \001(\0162\031.Protocol.EGameEnti"
  "tyType\022;\n\023entitye_look_at_dir\030\010 \001(\0162\036.Pr"
  "otocol.EGameEntityLookAtDir\0220\n\014entity_st"
  "ate\030\t \001(\0162\032.Protocol.EGameEntityState\"T\n"
  "\017GameMonsterInfo\022\022\n\nmonster_id\030\001 \001(\r\022-\n\013"
  "entity_info\030\002 \001(\0132\030.Protocol.GameEntityI"
  "nfob\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_Struct_2eproto_deps[1] = {
  &::descriptor_table_Enum_2eproto,
};
static ::_pbi::once_flag descriptor_table_Struct_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Struct_2eproto = {
    false, false, 411, descriptor_table_protodef_Struct_2eproto,
    "Struct.proto",
    &descriptor_table_Struct_2eproto_once, descriptor_table_Struct_2eproto_deps, 1, 2,
    schemas, file_default_instances, TableStruct_Struct_2eproto::offsets,
    file_level_metadata_Struct_2eproto, file_level_enum_descriptors_Struct_2eproto,
    file_level_service_descriptors_Struct_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Struct_2eproto_getter() {
  return &descriptor_table_Struct_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Struct_2eproto(&descriptor_table_Struct_2eproto);
namespace Protocol {

// ===================================================================

class GameEntityInfo::_Internal {
 public:
};

GameEntityInfo::GameEntityInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.GameEntityInfo)
}
GameEntityInfo::GameEntityInfo(const GameEntityInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GameEntityInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.entity_id_){}
    , decltype(_impl_.cell_pos_x_){}
    , decltype(_impl_.cell_pos_y_){}
    , decltype(_impl_.max_hp_){}
    , decltype(_impl_.hp_){}
    , decltype(_impl_.attack_){}
    , decltype(_impl_.entity_type_){}
    , decltype(_impl_.entitye_look_at_dir_){}
    , decltype(_impl_.entity_state_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.entity_id_, &from._impl_.entity_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.entity_state_) -
    reinterpret_cast<char*>(&_impl_.entity_id_)) + sizeof(_impl_.entity_state_));
  // @@protoc_insertion_point(copy_constructor:Protocol.GameEntityInfo)
}

inline void GameEntityInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.entity_id_){uint64_t{0u}}
    , decltype(_impl_.cell_pos_x_){0u}
    , decltype(_impl_.cell_pos_y_){0u}
    , decltype(_impl_.max_hp_){0u}
    , decltype(_impl_.hp_){0u}
    , decltype(_impl_.attack_){0u}
    , decltype(_impl_.entity_type_){0}
    , decltype(_impl_.entitye_look_at_dir_){0}
    , decltype(_impl_.entity_state_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GameEntityInfo::~GameEntityInfo() {
  // @@protoc_insertion_point(destructor:Protocol.GameEntityInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GameEntityInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void GameEntityInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GameEntityInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.GameEntityInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.entity_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.entity_state_) -
      reinterpret_cast<char*>(&_impl_.entity_id_)) + sizeof(_impl_.entity_state_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GameEntityInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 entity_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.entity_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 cell_pos_x = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.cell_pos_x_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 cell_pos_y = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.cell_pos_y_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 max_hp = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.max_hp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 hp = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.hp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 attack = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.attack_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Protocol.EGameEntityType entity_type = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_entity_type(static_cast<::Protocol::EGameEntityType>(val));
        } else
          goto handle_unusual;
        continue;
      // .Protocol.EGameEntityLookAtDir entitye_look_at_dir = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_entitye_look_at_dir(static_cast<::Protocol::EGameEntityLookAtDir>(val));
        } else
          goto handle_unusual;
        continue;
      // .Protocol.EGameEntityState entity_state = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_entity_state(static_cast<::Protocol::EGameEntityState>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GameEntityInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.GameEntityInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 entity_id = 1;
  if (this->_internal_entity_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_entity_id(), target);
  }

  // uint32 cell_pos_x = 2;
  if (this->_internal_cell_pos_x() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_cell_pos_x(), target);
  }

  // uint32 cell_pos_y = 3;
  if (this->_internal_cell_pos_y() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_cell_pos_y(), target);
  }

  // uint32 max_hp = 4;
  if (this->_internal_max_hp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_max_hp(), target);
  }

  // uint32 hp = 5;
  if (this->_internal_hp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(5, this->_internal_hp(), target);
  }

  // uint32 attack = 6;
  if (this->_internal_attack() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(6, this->_internal_attack(), target);
  }

  // .Protocol.EGameEntityType entity_type = 7;
  if (this->_internal_entity_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      7, this->_internal_entity_type(), target);
  }

  // .Protocol.EGameEntityLookAtDir entitye_look_at_dir = 8;
  if (this->_internal_entitye_look_at_dir() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      8, this->_internal_entitye_look_at_dir(), target);
  }

  // .Protocol.EGameEntityState entity_state = 9;
  if (this->_internal_entity_state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      9, this->_internal_entity_state(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.GameEntityInfo)
  return target;
}

size_t GameEntityInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.GameEntityInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 entity_id = 1;
  if (this->_internal_entity_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_entity_id());
  }

  // uint32 cell_pos_x = 2;
  if (this->_internal_cell_pos_x() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_cell_pos_x());
  }

  // uint32 cell_pos_y = 3;
  if (this->_internal_cell_pos_y() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_cell_pos_y());
  }

  // uint32 max_hp = 4;
  if (this->_internal_max_hp() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_max_hp());
  }

  // uint32 hp = 5;
  if (this->_internal_hp() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_hp());
  }

  // uint32 attack = 6;
  if (this->_internal_attack() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_attack());
  }

  // .Protocol.EGameEntityType entity_type = 7;
  if (this->_internal_entity_type() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_entity_type());
  }

  // .Protocol.EGameEntityLookAtDir entitye_look_at_dir = 8;
  if (this->_internal_entitye_look_at_dir() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_entitye_look_at_dir());
  }

  // .Protocol.EGameEntityState entity_state = 9;
  if (this->_internal_entity_state() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_entity_state());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GameEntityInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GameEntityInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GameEntityInfo::GetClassData() const { return &_class_data_; }


void GameEntityInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GameEntityInfo*>(&to_msg);
  auto& from = static_cast<const GameEntityInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.GameEntityInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_entity_id() != 0) {
    _this->_internal_set_entity_id(from._internal_entity_id());
  }
  if (from._internal_cell_pos_x() != 0) {
    _this->_internal_set_cell_pos_x(from._internal_cell_pos_x());
  }
  if (from._internal_cell_pos_y() != 0) {
    _this->_internal_set_cell_pos_y(from._internal_cell_pos_y());
  }
  if (from._internal_max_hp() != 0) {
    _this->_internal_set_max_hp(from._internal_max_hp());
  }
  if (from._internal_hp() != 0) {
    _this->_internal_set_hp(from._internal_hp());
  }
  if (from._internal_attack() != 0) {
    _this->_internal_set_attack(from._internal_attack());
  }
  if (from._internal_entity_type() != 0) {
    _this->_internal_set_entity_type(from._internal_entity_type());
  }
  if (from._internal_entitye_look_at_dir() != 0) {
    _this->_internal_set_entitye_look_at_dir(from._internal_entitye_look_at_dir());
  }
  if (from._internal_entity_state() != 0) {
    _this->_internal_set_entity_state(from._internal_entity_state());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GameEntityInfo::CopyFrom(const GameEntityInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.GameEntityInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GameEntityInfo::IsInitialized() const {
  return true;
}

void GameEntityInfo::InternalSwap(GameEntityInfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GameEntityInfo, _impl_.entity_state_)
      + sizeof(GameEntityInfo::_impl_.entity_state_)
      - PROTOBUF_FIELD_OFFSET(GameEntityInfo, _impl_.entity_id_)>(
          reinterpret_cast<char*>(&_impl_.entity_id_),
          reinterpret_cast<char*>(&other->_impl_.entity_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GameEntityInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Struct_2eproto_getter, &descriptor_table_Struct_2eproto_once,
      file_level_metadata_Struct_2eproto[0]);
}

// ===================================================================

class GameMonsterInfo::_Internal {
 public:
  static const ::Protocol::GameEntityInfo& entity_info(const GameMonsterInfo* msg);
};

const ::Protocol::GameEntityInfo&
GameMonsterInfo::_Internal::entity_info(const GameMonsterInfo* msg) {
  return *msg->_impl_.entity_info_;
}
GameMonsterInfo::GameMonsterInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.GameMonsterInfo)
}
GameMonsterInfo::GameMonsterInfo(const GameMonsterInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GameMonsterInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.entity_info_){nullptr}
    , decltype(_impl_.monster_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_entity_info()) {
    _this->_impl_.entity_info_ = new ::Protocol::GameEntityInfo(*from._impl_.entity_info_);
  }
  _this->_impl_.monster_id_ = from._impl_.monster_id_;
  // @@protoc_insertion_point(copy_constructor:Protocol.GameMonsterInfo)
}

inline void GameMonsterInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.entity_info_){nullptr}
    , decltype(_impl_.monster_id_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GameMonsterInfo::~GameMonsterInfo() {
  // @@protoc_insertion_point(destructor:Protocol.GameMonsterInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GameMonsterInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.entity_info_;
}

void GameMonsterInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GameMonsterInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.GameMonsterInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.entity_info_ != nullptr) {
    delete _impl_.entity_info_;
  }
  _impl_.entity_info_ = nullptr;
  _impl_.monster_id_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GameMonsterInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 monster_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.monster_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .Protocol.GameEntityInfo entity_info = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_entity_info(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GameMonsterInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.GameMonsterInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 monster_id = 1;
  if (this->_internal_monster_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_monster_id(), target);
  }

  // .Protocol.GameEntityInfo entity_info = 2;
  if (this->_internal_has_entity_info()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::entity_info(this),
        _Internal::entity_info(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.GameMonsterInfo)
  return target;
}

size_t GameMonsterInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.GameMonsterInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Protocol.GameEntityInfo entity_info = 2;
  if (this->_internal_has_entity_info()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.entity_info_);
  }

  // uint32 monster_id = 1;
  if (this->_internal_monster_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_monster_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GameMonsterInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GameMonsterInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GameMonsterInfo::GetClassData() const { return &_class_data_; }


void GameMonsterInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GameMonsterInfo*>(&to_msg);
  auto& from = static_cast<const GameMonsterInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.GameMonsterInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_entity_info()) {
    _this->_internal_mutable_entity_info()->::Protocol::GameEntityInfo::MergeFrom(
        from._internal_entity_info());
  }
  if (from._internal_monster_id() != 0) {
    _this->_internal_set_monster_id(from._internal_monster_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GameMonsterInfo::CopyFrom(const GameMonsterInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.GameMonsterInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GameMonsterInfo::IsInitialized() const {
  return true;
}

void GameMonsterInfo::InternalSwap(GameMonsterInfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GameMonsterInfo, _impl_.monster_id_)
      + sizeof(GameMonsterInfo::_impl_.monster_id_)
      - PROTOBUF_FIELD_OFFSET(GameMonsterInfo, _impl_.entity_info_)>(
          reinterpret_cast<char*>(&_impl_.entity_info_),
          reinterpret_cast<char*>(&other->_impl_.entity_info_));
}

::PROTOBUF_NAMESPACE_ID::Metadata GameMonsterInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Struct_2eproto_getter, &descriptor_table_Struct_2eproto_once,
      file_level_metadata_Struct_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::GameEntityInfo*
Arena::CreateMaybeMessage< ::Protocol::GameEntityInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::GameEntityInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::GameMonsterInfo*
Arena::CreateMaybeMessage< ::Protocol::GameMonsterInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::GameMonsterInfo >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
