// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Struct.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Struct_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Struct_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Struct_2eproto;
namespace Protocol {
class GameEntityInfo;
struct GameEntityInfoDefaultTypeInternal;
extern GameEntityInfoDefaultTypeInternal _GameEntityInfo_default_instance_;
class GameMonsterInfo;
struct GameMonsterInfoDefaultTypeInternal;
extern GameMonsterInfoDefaultTypeInternal _GameMonsterInfo_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::GameEntityInfo* Arena::CreateMaybeMessage<::Protocol::GameEntityInfo>(Arena*);
template<> ::Protocol::GameMonsterInfo* Arena::CreateMaybeMessage<::Protocol::GameMonsterInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class GameEntityInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.GameEntityInfo) */ {
 public:
  inline GameEntityInfo() : GameEntityInfo(nullptr) {}
  ~GameEntityInfo() override;
  explicit PROTOBUF_CONSTEXPR GameEntityInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GameEntityInfo(const GameEntityInfo& from);
  GameEntityInfo(GameEntityInfo&& from) noexcept
    : GameEntityInfo() {
    *this = ::std::move(from);
  }

  inline GameEntityInfo& operator=(const GameEntityInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline GameEntityInfo& operator=(GameEntityInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GameEntityInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const GameEntityInfo* internal_default_instance() {
    return reinterpret_cast<const GameEntityInfo*>(
               &_GameEntityInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GameEntityInfo& a, GameEntityInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(GameEntityInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GameEntityInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GameEntityInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GameEntityInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GameEntityInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GameEntityInfo& from) {
    GameEntityInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameEntityInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.GameEntityInfo";
  }
  protected:
  explicit GameEntityInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEntityIdFieldNumber = 1,
    kCellPosXFieldNumber = 2,
    kCellPosYFieldNumber = 3,
    kMaxHpFieldNumber = 4,
    kHpFieldNumber = 5,
    kAttackFieldNumber = 6,
    kDefenseFieldNumber = 7,
    kEntityTypeFieldNumber = 8,
    kEntityeLookAtDirFieldNumber = 9,
    kEntityStateFieldNumber = 10,
  };
  // uint64 entity_id = 1;
  void clear_entity_id();
  uint64_t entity_id() const;
  void set_entity_id(uint64_t value);
  private:
  uint64_t _internal_entity_id() const;
  void _internal_set_entity_id(uint64_t value);
  public:

  // uint32 cell_pos_x = 2;
  void clear_cell_pos_x();
  uint32_t cell_pos_x() const;
  void set_cell_pos_x(uint32_t value);
  private:
  uint32_t _internal_cell_pos_x() const;
  void _internal_set_cell_pos_x(uint32_t value);
  public:

  // uint32 cell_pos_y = 3;
  void clear_cell_pos_y();
  uint32_t cell_pos_y() const;
  void set_cell_pos_y(uint32_t value);
  private:
  uint32_t _internal_cell_pos_y() const;
  void _internal_set_cell_pos_y(uint32_t value);
  public:

  // int32 max_hp = 4;
  void clear_max_hp();
  int32_t max_hp() const;
  void set_max_hp(int32_t value);
  private:
  int32_t _internal_max_hp() const;
  void _internal_set_max_hp(int32_t value);
  public:

  // int32 hp = 5;
  void clear_hp();
  int32_t hp() const;
  void set_hp(int32_t value);
  private:
  int32_t _internal_hp() const;
  void _internal_set_hp(int32_t value);
  public:

  // uint32 attack = 6;
  void clear_attack();
  uint32_t attack() const;
  void set_attack(uint32_t value);
  private:
  uint32_t _internal_attack() const;
  void _internal_set_attack(uint32_t value);
  public:

  // uint32 defense = 7;
  void clear_defense();
  uint32_t defense() const;
  void set_defense(uint32_t value);
  private:
  uint32_t _internal_defense() const;
  void _internal_set_defense(uint32_t value);
  public:

  // .Protocol.EGameEntityType entity_type = 8;
  void clear_entity_type();
  ::Protocol::EGameEntityType entity_type() const;
  void set_entity_type(::Protocol::EGameEntityType value);
  private:
  ::Protocol::EGameEntityType _internal_entity_type() const;
  void _internal_set_entity_type(::Protocol::EGameEntityType value);
  public:

  // .Protocol.EGameEntityLookAtDir entitye_look_at_dir = 9;
  void clear_entitye_look_at_dir();
  ::Protocol::EGameEntityLookAtDir entitye_look_at_dir() const;
  void set_entitye_look_at_dir(::Protocol::EGameEntityLookAtDir value);
  private:
  ::Protocol::EGameEntityLookAtDir _internal_entitye_look_at_dir() const;
  void _internal_set_entitye_look_at_dir(::Protocol::EGameEntityLookAtDir value);
  public:

  // .Protocol.EGameEntityState entity_state = 10;
  void clear_entity_state();
  ::Protocol::EGameEntityState entity_state() const;
  void set_entity_state(::Protocol::EGameEntityState value);
  private:
  ::Protocol::EGameEntityState _internal_entity_state() const;
  void _internal_set_entity_state(::Protocol::EGameEntityState value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.GameEntityInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t entity_id_;
    uint32_t cell_pos_x_;
    uint32_t cell_pos_y_;
    int32_t max_hp_;
    int32_t hp_;
    uint32_t attack_;
    uint32_t defense_;
    int entity_type_;
    int entitye_look_at_dir_;
    int entity_state_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class GameMonsterInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.GameMonsterInfo) */ {
 public:
  inline GameMonsterInfo() : GameMonsterInfo(nullptr) {}
  ~GameMonsterInfo() override;
  explicit PROTOBUF_CONSTEXPR GameMonsterInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GameMonsterInfo(const GameMonsterInfo& from);
  GameMonsterInfo(GameMonsterInfo&& from) noexcept
    : GameMonsterInfo() {
    *this = ::std::move(from);
  }

  inline GameMonsterInfo& operator=(const GameMonsterInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline GameMonsterInfo& operator=(GameMonsterInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GameMonsterInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const GameMonsterInfo* internal_default_instance() {
    return reinterpret_cast<const GameMonsterInfo*>(
               &_GameMonsterInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GameMonsterInfo& a, GameMonsterInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(GameMonsterInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GameMonsterInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GameMonsterInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GameMonsterInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GameMonsterInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GameMonsterInfo& from) {
    GameMonsterInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameMonsterInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.GameMonsterInfo";
  }
  protected:
  explicit GameMonsterInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEntityInfoFieldNumber = 2,
    kMonsterIdFieldNumber = 1,
  };
  // .Protocol.GameEntityInfo entity_info = 2;
  bool has_entity_info() const;
  private:
  bool _internal_has_entity_info() const;
  public:
  void clear_entity_info();
  const ::Protocol::GameEntityInfo& entity_info() const;
  PROTOBUF_NODISCARD ::Protocol::GameEntityInfo* release_entity_info();
  ::Protocol::GameEntityInfo* mutable_entity_info();
  void set_allocated_entity_info(::Protocol::GameEntityInfo* entity_info);
  private:
  const ::Protocol::GameEntityInfo& _internal_entity_info() const;
  ::Protocol::GameEntityInfo* _internal_mutable_entity_info();
  public:
  void unsafe_arena_set_allocated_entity_info(
      ::Protocol::GameEntityInfo* entity_info);
  ::Protocol::GameEntityInfo* unsafe_arena_release_entity_info();

  // uint32 monster_id = 1;
  void clear_monster_id();
  uint32_t monster_id() const;
  void set_monster_id(uint32_t value);
  private:
  uint32_t _internal_monster_id() const;
  void _internal_set_monster_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.GameMonsterInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Protocol::GameEntityInfo* entity_info_;
    uint32_t monster_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GameEntityInfo

// uint64 entity_id = 1;
inline void GameEntityInfo::clear_entity_id() {
  _impl_.entity_id_ = uint64_t{0u};
}
inline uint64_t GameEntityInfo::_internal_entity_id() const {
  return _impl_.entity_id_;
}
inline uint64_t GameEntityInfo::entity_id() const {
  // @@protoc_insertion_point(field_get:Protocol.GameEntityInfo.entity_id)
  return _internal_entity_id();
}
inline void GameEntityInfo::_internal_set_entity_id(uint64_t value) {
  
  _impl_.entity_id_ = value;
}
inline void GameEntityInfo::set_entity_id(uint64_t value) {
  _internal_set_entity_id(value);
  // @@protoc_insertion_point(field_set:Protocol.GameEntityInfo.entity_id)
}

// uint32 cell_pos_x = 2;
inline void GameEntityInfo::clear_cell_pos_x() {
  _impl_.cell_pos_x_ = 0u;
}
inline uint32_t GameEntityInfo::_internal_cell_pos_x() const {
  return _impl_.cell_pos_x_;
}
inline uint32_t GameEntityInfo::cell_pos_x() const {
  // @@protoc_insertion_point(field_get:Protocol.GameEntityInfo.cell_pos_x)
  return _internal_cell_pos_x();
}
inline void GameEntityInfo::_internal_set_cell_pos_x(uint32_t value) {
  
  _impl_.cell_pos_x_ = value;
}
inline void GameEntityInfo::set_cell_pos_x(uint32_t value) {
  _internal_set_cell_pos_x(value);
  // @@protoc_insertion_point(field_set:Protocol.GameEntityInfo.cell_pos_x)
}

// uint32 cell_pos_y = 3;
inline void GameEntityInfo::clear_cell_pos_y() {
  _impl_.cell_pos_y_ = 0u;
}
inline uint32_t GameEntityInfo::_internal_cell_pos_y() const {
  return _impl_.cell_pos_y_;
}
inline uint32_t GameEntityInfo::cell_pos_y() const {
  // @@protoc_insertion_point(field_get:Protocol.GameEntityInfo.cell_pos_y)
  return _internal_cell_pos_y();
}
inline void GameEntityInfo::_internal_set_cell_pos_y(uint32_t value) {
  
  _impl_.cell_pos_y_ = value;
}
inline void GameEntityInfo::set_cell_pos_y(uint32_t value) {
  _internal_set_cell_pos_y(value);
  // @@protoc_insertion_point(field_set:Protocol.GameEntityInfo.cell_pos_y)
}

// int32 max_hp = 4;
inline void GameEntityInfo::clear_max_hp() {
  _impl_.max_hp_ = 0;
}
inline int32_t GameEntityInfo::_internal_max_hp() const {
  return _impl_.max_hp_;
}
inline int32_t GameEntityInfo::max_hp() const {
  // @@protoc_insertion_point(field_get:Protocol.GameEntityInfo.max_hp)
  return _internal_max_hp();
}
inline void GameEntityInfo::_internal_set_max_hp(int32_t value) {
  
  _impl_.max_hp_ = value;
}
inline void GameEntityInfo::set_max_hp(int32_t value) {
  _internal_set_max_hp(value);
  // @@protoc_insertion_point(field_set:Protocol.GameEntityInfo.max_hp)
}

// int32 hp = 5;
inline void GameEntityInfo::clear_hp() {
  _impl_.hp_ = 0;
}
inline int32_t GameEntityInfo::_internal_hp() const {
  return _impl_.hp_;
}
inline int32_t GameEntityInfo::hp() const {
  // @@protoc_insertion_point(field_get:Protocol.GameEntityInfo.hp)
  return _internal_hp();
}
inline void GameEntityInfo::_internal_set_hp(int32_t value) {
  
  _impl_.hp_ = value;
}
inline void GameEntityInfo::set_hp(int32_t value) {
  _internal_set_hp(value);
  // @@protoc_insertion_point(field_set:Protocol.GameEntityInfo.hp)
}

// uint32 attack = 6;
inline void GameEntityInfo::clear_attack() {
  _impl_.attack_ = 0u;
}
inline uint32_t GameEntityInfo::_internal_attack() const {
  return _impl_.attack_;
}
inline uint32_t GameEntityInfo::attack() const {
  // @@protoc_insertion_point(field_get:Protocol.GameEntityInfo.attack)
  return _internal_attack();
}
inline void GameEntityInfo::_internal_set_attack(uint32_t value) {
  
  _impl_.attack_ = value;
}
inline void GameEntityInfo::set_attack(uint32_t value) {
  _internal_set_attack(value);
  // @@protoc_insertion_point(field_set:Protocol.GameEntityInfo.attack)
}

// uint32 defense = 7;
inline void GameEntityInfo::clear_defense() {
  _impl_.defense_ = 0u;
}
inline uint32_t GameEntityInfo::_internal_defense() const {
  return _impl_.defense_;
}
inline uint32_t GameEntityInfo::defense() const {
  // @@protoc_insertion_point(field_get:Protocol.GameEntityInfo.defense)
  return _internal_defense();
}
inline void GameEntityInfo::_internal_set_defense(uint32_t value) {
  
  _impl_.defense_ = value;
}
inline void GameEntityInfo::set_defense(uint32_t value) {
  _internal_set_defense(value);
  // @@protoc_insertion_point(field_set:Protocol.GameEntityInfo.defense)
}

// .Protocol.EGameEntityType entity_type = 8;
inline void GameEntityInfo::clear_entity_type() {
  _impl_.entity_type_ = 0;
}
inline ::Protocol::EGameEntityType GameEntityInfo::_internal_entity_type() const {
  return static_cast< ::Protocol::EGameEntityType >(_impl_.entity_type_);
}
inline ::Protocol::EGameEntityType GameEntityInfo::entity_type() const {
  // @@protoc_insertion_point(field_get:Protocol.GameEntityInfo.entity_type)
  return _internal_entity_type();
}
inline void GameEntityInfo::_internal_set_entity_type(::Protocol::EGameEntityType value) {
  
  _impl_.entity_type_ = value;
}
inline void GameEntityInfo::set_entity_type(::Protocol::EGameEntityType value) {
  _internal_set_entity_type(value);
  // @@protoc_insertion_point(field_set:Protocol.GameEntityInfo.entity_type)
}

// .Protocol.EGameEntityLookAtDir entitye_look_at_dir = 9;
inline void GameEntityInfo::clear_entitye_look_at_dir() {
  _impl_.entitye_look_at_dir_ = 0;
}
inline ::Protocol::EGameEntityLookAtDir GameEntityInfo::_internal_entitye_look_at_dir() const {
  return static_cast< ::Protocol::EGameEntityLookAtDir >(_impl_.entitye_look_at_dir_);
}
inline ::Protocol::EGameEntityLookAtDir GameEntityInfo::entitye_look_at_dir() const {
  // @@protoc_insertion_point(field_get:Protocol.GameEntityInfo.entitye_look_at_dir)
  return _internal_entitye_look_at_dir();
}
inline void GameEntityInfo::_internal_set_entitye_look_at_dir(::Protocol::EGameEntityLookAtDir value) {
  
  _impl_.entitye_look_at_dir_ = value;
}
inline void GameEntityInfo::set_entitye_look_at_dir(::Protocol::EGameEntityLookAtDir value) {
  _internal_set_entitye_look_at_dir(value);
  // @@protoc_insertion_point(field_set:Protocol.GameEntityInfo.entitye_look_at_dir)
}

// .Protocol.EGameEntityState entity_state = 10;
inline void GameEntityInfo::clear_entity_state() {
  _impl_.entity_state_ = 0;
}
inline ::Protocol::EGameEntityState GameEntityInfo::_internal_entity_state() const {
  return static_cast< ::Protocol::EGameEntityState >(_impl_.entity_state_);
}
inline ::Protocol::EGameEntityState GameEntityInfo::entity_state() const {
  // @@protoc_insertion_point(field_get:Protocol.GameEntityInfo.entity_state)
  return _internal_entity_state();
}
inline void GameEntityInfo::_internal_set_entity_state(::Protocol::EGameEntityState value) {
  
  _impl_.entity_state_ = value;
}
inline void GameEntityInfo::set_entity_state(::Protocol::EGameEntityState value) {
  _internal_set_entity_state(value);
  // @@protoc_insertion_point(field_set:Protocol.GameEntityInfo.entity_state)
}

// -------------------------------------------------------------------

// GameMonsterInfo

// uint32 monster_id = 1;
inline void GameMonsterInfo::clear_monster_id() {
  _impl_.monster_id_ = 0u;
}
inline uint32_t GameMonsterInfo::_internal_monster_id() const {
  return _impl_.monster_id_;
}
inline uint32_t GameMonsterInfo::monster_id() const {
  // @@protoc_insertion_point(field_get:Protocol.GameMonsterInfo.monster_id)
  return _internal_monster_id();
}
inline void GameMonsterInfo::_internal_set_monster_id(uint32_t value) {
  
  _impl_.monster_id_ = value;
}
inline void GameMonsterInfo::set_monster_id(uint32_t value) {
  _internal_set_monster_id(value);
  // @@protoc_insertion_point(field_set:Protocol.GameMonsterInfo.monster_id)
}

// .Protocol.GameEntityInfo entity_info = 2;
inline bool GameMonsterInfo::_internal_has_entity_info() const {
  return this != internal_default_instance() && _impl_.entity_info_ != nullptr;
}
inline bool GameMonsterInfo::has_entity_info() const {
  return _internal_has_entity_info();
}
inline void GameMonsterInfo::clear_entity_info() {
  if (GetArenaForAllocation() == nullptr && _impl_.entity_info_ != nullptr) {
    delete _impl_.entity_info_;
  }
  _impl_.entity_info_ = nullptr;
}
inline const ::Protocol::GameEntityInfo& GameMonsterInfo::_internal_entity_info() const {
  const ::Protocol::GameEntityInfo* p = _impl_.entity_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::GameEntityInfo&>(
      ::Protocol::_GameEntityInfo_default_instance_);
}
inline const ::Protocol::GameEntityInfo& GameMonsterInfo::entity_info() const {
  // @@protoc_insertion_point(field_get:Protocol.GameMonsterInfo.entity_info)
  return _internal_entity_info();
}
inline void GameMonsterInfo::unsafe_arena_set_allocated_entity_info(
    ::Protocol::GameEntityInfo* entity_info) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.entity_info_);
  }
  _impl_.entity_info_ = entity_info;
  if (entity_info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.GameMonsterInfo.entity_info)
}
inline ::Protocol::GameEntityInfo* GameMonsterInfo::release_entity_info() {
  
  ::Protocol::GameEntityInfo* temp = _impl_.entity_info_;
  _impl_.entity_info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::GameEntityInfo* GameMonsterInfo::unsafe_arena_release_entity_info() {
  // @@protoc_insertion_point(field_release:Protocol.GameMonsterInfo.entity_info)
  
  ::Protocol::GameEntityInfo* temp = _impl_.entity_info_;
  _impl_.entity_info_ = nullptr;
  return temp;
}
inline ::Protocol::GameEntityInfo* GameMonsterInfo::_internal_mutable_entity_info() {
  
  if (_impl_.entity_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::GameEntityInfo>(GetArenaForAllocation());
    _impl_.entity_info_ = p;
  }
  return _impl_.entity_info_;
}
inline ::Protocol::GameEntityInfo* GameMonsterInfo::mutable_entity_info() {
  ::Protocol::GameEntityInfo* _msg = _internal_mutable_entity_info();
  // @@protoc_insertion_point(field_mutable:Protocol.GameMonsterInfo.entity_info)
  return _msg;
}
inline void GameMonsterInfo::set_allocated_entity_info(::Protocol::GameEntityInfo* entity_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.entity_info_;
  }
  if (entity_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(entity_info);
    if (message_arena != submessage_arena) {
      entity_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, entity_info, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.entity_info_ = entity_info;
  // @@protoc_insertion_point(field_set_allocated:Protocol.GameMonsterInfo.entity_info)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
