// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Enum.proto
// Protobuf C++ Version: 5.29.0-dev

#ifndef GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Enum_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Enum_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Enum_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Protocol {
enum EPlayerType : int {
  PlayerTypeNone = 0,
  PlayerTypeKnight = 1,
  PlayerTypeMage = 2,
  PlayerTypeArcher = 3,
  EPlayerType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  EPlayerType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool EPlayerType_IsValid(int value);
extern const uint32_t EPlayerType_internal_data_[];
constexpr EPlayerType EPlayerType_MIN = static_cast<EPlayerType>(0);
constexpr EPlayerType EPlayerType_MAX = static_cast<EPlayerType>(3);
constexpr int EPlayerType_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
EPlayerType_descriptor();
template <typename T>
const std::string& EPlayerType_Name(T value) {
  static_assert(std::is_same<T, EPlayerType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to EPlayerType_Name().");
  return EPlayerType_Name(static_cast<EPlayerType>(value));
}
template <>
inline const std::string& EPlayerType_Name(EPlayerType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<EPlayerType_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool EPlayerType_Parse(absl::string_view name, EPlayerType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EPlayerType>(
      EPlayerType_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Protocol::EPlayerType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::EPlayerType>() {
  return ::Protocol::EPlayerType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto_2epb_2eh
